from . import counselling_sub_stages
from . import configuration
from . import base_model
from . import refraction_1
from . import history
from . import doctor
from . import optics
from . import registration
from . import patient_visit_tags
from . import iol
from . import surgery
from . import old_glass_wizard
from . import refraction_2
from . import counselling
from . import sale
from . import work_order
from . import optics_config
from . import medical_patient
from . import product
from . import appoinment_system
from . import invoice
from . import stock_picking
from . import account_journal
from . import purchase_order
from . import product_product
from . import treatment
from . import medical_refractionist
from . import procedure
from . import investigation_procedure
