{
    'name': 'Medical-Opthalmology',
    'version': '10.0.1.0.0',
    'author': 'Odox SoftHub',
    'maintainer': 'ACSONE SA/NV, Odoo Community Association (OCA)',
    'website': 'http://www.odoxsofthub.com',
    'license': 'GPL-3',
    'category': 'Medical',
    'depends': ['base',
        'medical','medical_practitioner','sale_stock','account','sale_discount_total','stock_mts_mto_rule','purchase',
                'account_voucher','purchase_total_discount','odx_web_ribbon_widget'
    ],
    'summary': 'Introduce medication notion into the medical addons',
    'data': [
        'views/back_end.xml',
        'security/opthalmology_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/model_sub_state_data.xml',
        'data/eye_value_data.xml',
        'data/eye_value_axis.xml',
        'data/eye_value_va.xml',
        'views/refraction_1_page.xml',
        'views/refraction_2_page.xml',
        'views/old_glass_form_view.xml',
        'views/doctor_view.xml',
        'views/iol_view.xml',
        'views/history.xml',
        'views/optics_view.xml',
        'views/counselling_view.xml',
        'views/registration_view.xml',
        'views/patient_visit_tag_view.xml',
        'views/surgery_view.xml',
        'views/counselling_sub_stage_view.xml',
        'views/work_order.xml',
        'views/old_glass_wizard_view.xml',
        'report/report.xml',
        'report/report_registration_slip.xml',
        'report/report_registration_invoice.xml',
        'report/print_prescription_report.xml',
        'views/settings_view.xml',
        'views/medical_patient_view.xml',
        'views/product_view.xml',
        'views/sale_views.xml',
        'views/account_journal_view.xml',
        'wizard/doctor_warning_wizard_view.xml',
        'wizard/eye_value_wizard_view.xml',
        'wizard/forward_wizard_view.xml',
        'wizard/registration_warning_wizard.xml',
        'wizard/counselling_appointment_view.xml',
        'views/reference_view.xml',
        'views/appointment_view.xml',
        'views/new_patient_view.xml',
        'report/print_eye_details_template.xml',
        'report/print_work_order_template.xml',
        'views/invoices_views.xml',
        'report/regisration_report_pivot_view.xml',
        'report/investigation_report_pivot_view.xml',
        'report/surgery_report_pivot_view.xml',
        'report/optics_report_pivot_view.xml',
        'report/pharmacy_report_pivot_view.xml',
        'views/booleans_view.xml',
        'report/payments_report_pivots.xml',
        'report/medical_report.xml',
        'report/layout.xml',
        'views/purchase_order_view.xml',
        'views/purchase_optics_frame.xml',
        'views/purchase_optics_lense.xml',
        'views/purchase_iol_products.xml',
        'views/account_voucher.xml',
        'views/medical_refractionist_view.xml',
        'report/iol_detail_template.xml',
        'views/procedure.xml',
        'wizard/dilation_wizard_view.xml',
        'wizard/medicine_list_wizard_view.xml',
        'data/reset_sequence.xml',
        'views/pharmacy_frequency.xml',
        # 'views/investigation_procedure_view.xml'



    ],
    'installable': True,
    'auto_install': False,
}
